"""team table

Revision ID: 09fdacf2585b
Revises: a864602a5a78
Create Date: 2025-03-22 21:37:25.708253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09fdacf2585b'
down_revision = 'a864602a5a78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'team')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('team', postgresql.ARRAY(postgresql.UUID()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
