"""team table refac

Revision ID: 0a9e5f06565f
Revises: e956ef3aecb4
Create Date: 2025-03-22 21:48:06.237783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9e5f06565f'
down_revision = 'e956ef3aecb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
