"""Team add ARRAY type

Revision ID: 1b14c1cf540e
Revises: d8f8a1d8468c
Create Date: 2025-03-22 20:17:31.782704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b14c1cf540e'
down_revision = 'd8f8a1d8468c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
