"""array куафс

Revision ID: 3af63aa98efc
Revises: 1c55ad717658
Create Date: 2025-03-22 20:39:34.479826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3af63aa98efc'
down_revision = '1c55ad717658'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('teamlid_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('team', postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    # ### end Alembic commands ###
