"""array

Revision ID: 4570cade37cc
Revises: 1b14c1cf540e
Create Date: 2025-03-22 20:31:29.081276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4570cade37cc'
down_revision = '1b14c1cf540e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
