"""userandteam ewr

Revision ID: 470f55dd5408
Revises: 0a9e5f06565f
Create Date: 2025-03-22 22:04:07.843599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470f55dd5408'
down_revision = '0a9e5f06565f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
