"""userandteam asdas

Revision ID: c1c3a337e0f1
Revises: dd99462db40d
Create Date: 2025-03-22 22:17:01.440363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c3a337e0f1'
down_revision = 'dd99462db40d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
