"""new table

Revision ID: d8f8a1d8468c
Revises: 
Create Date: 2025-03-22 20:12:21.942667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8f8a1d8468c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('responsible', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('teams',
    sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('teamlid_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('team', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('tasks')
    # ### end Alembic commands ###
