"""team table rasdsadas

Revision ID: dd99462db40d
Revises: 470f55dd5408
Create Date: 2025-03-22 22:12:28.728831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd99462db40d'
down_revision = '470f55dd5408'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userandteam', 'team_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('users', 'invite_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'invite_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('userandteam', 'team_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
