"""userandteam None

Revision ID: e956ef3aecb4
Revises: 09fdacf2585b
Create Date: 2025-03-22 21:43:35.887529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e956ef3aecb4'
down_revision = '09fdacf2585b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
